#ifndef MIXSISCTRL
#define MIXSISCTRL

#include <QSlider>
#include <QCheckBox>
#include <QComboBox>
#include <QRadioButton>
//#include "mixsis.h"

enum alsa_numid {
    MSTR_SWITCH = 4, MSTR_VOL, OUT_SWITCH_12, OUT_VOL_12, OUT_1_SRC, OUT_2_SRC,
    OUT_SWITCH_34, OUT_VOL_34, OUT_3_SRC, OUT_4_SRC, OUT_SWITCH_56, OUT_VOL_56,
    OUT_5_SRC, OUT_6_SRC, IN_IMP_1, IN_PAD_1, IN_IMP_2, IN_PAD_2, IN_PAD_3, IN_PAD_4,
    MATRIX_ROUTE_1, MATRIX_A_1, MATRIX_B_1, MATRIX_C_1, MATRIX_D_1, MATRIX_E_1, MATRIX_F_1, MATRIX_G_1, MATRIX_H_1,
    MATRIX_ROUTE_2, MATRIX_A_2, MATRIX_B_2, MATRIX_C_2, MATRIX_D_2, MATRIX_E_2, MATRIX_F_2, MATRIX_G_2, MATRIX_H_2,
    MATRIX_ROUTE_3, MATRIX_A_3, MATRIX_B_3, MATRIX_C_3, MATRIX_D_3, MATRIX_E_3, MATRIX_F_3, MATRIX_G_3, MATRIX_H_3,
    MATRIX_ROUTE_4, MATRIX_A_4, MATRIX_B_4, MATRIX_C_4, MATRIX_D_4, MATRIX_E_4, MATRIX_F_4, MATRIX_G_4, MATRIX_H_4,
    MATRIX_ROUTE_5, MATRIX_A_5, MATRIX_B_5, MATRIX_C_5, MATRIX_D_5, MATRIX_E_5, MATRIX_F_5, MATRIX_G_5, MATRIX_H_5,
    MATRIX_ROUTE_6, MATRIX_A_6, MATRIX_B_6, MATRIX_C_6, MATRIX_D_6, MATRIX_E_6, MATRIX_F_6, MATRIX_G_6, MATRIX_H_6,
    MATRIX_ROUTE_7, MATRIX_A_7, MATRIX_B_7, MATRIX_C_7, MATRIX_D_7, MATRIX_E_7, MATRIX_F_7, MATRIX_G_7, MATRIX_H_7,
    MATRIX_ROUTE_8, MATRIX_A_8, MATRIX_B_8, MATRIX_C_8, MATRIX_D_8, MATRIX_E_8, MATRIX_F_8, MATRIX_G_8, MATRIX_H_8,
    MATRIX_ROUTE_9, MATRIX_A_9, MATRIX_B_9, MATRIX_C_9, MATRIX_D_9, MATRIX_E_9, MATRIX_F_9, MATRIX_G_9, MATRIX_H_9,
    MATRIX_ROUTE_10, MATRIX_A_10, MATRIX_B_10, MATRIX_C_10, MATRIX_D_10, MATRIX_E_10, MATRIX_F_10, MATRIX_G_10, MATRIX_H_10,
    MATRIX_ROUTE_11, MATRIX_A_11, MATRIX_B_11, MATRIX_C_11, MATRIX_D_11, MATRIX_E_11, MATRIX_F_11, MATRIX_G_11, MATRIX_H_11,
    MATRIX_ROUTE_12, MATRIX_A_12, MATRIX_B_12, MATRIX_C_12, MATRIX_D_12, MATRIX_E_12, MATRIX_F_12, MATRIX_G_12, MATRIX_H_12,
    MATRIX_ROUTE_13, MATRIX_A_13, MATRIX_B_13, MATRIX_C_13, MATRIX_D_13, MATRIX_E_13, MATRIX_F_13, MATRIX_G_13, MATRIX_H_13,
    MATRIX_ROUTE_14, MATRIX_A_14, MATRIX_B_14, MATRIX_C_14, MATRIX_D_14, MATRIX_E_14, MATRIX_F_14, MATRIX_G_14, MATRIX_H_14,
    MATRIX_ROUTE_15, MATRIX_A_15, MATRIX_B_15, MATRIX_C_15, MATRIX_D_15, MATRIX_E_15, MATRIX_F_15, MATRIX_G_15, MATRIX_H_15,
    MATRIX_ROUTE_16, MATRIX_A_16, MATRIX_B_16, MATRIX_C_16, MATRIX_D_16, MATRIX_E_16, MATRIX_F_16, MATRIX_G_16, MATRIX_H_16,
    MATRIX_ROUTE_17, MATRIX_A_17, MATRIX_B_17, MATRIX_C_17, MATRIX_D_17, MATRIX_E_17, MATRIX_F_17, MATRIX_G_17, MATRIX_H_17,
    MATRIX_ROUTE_18, MATRIX_A_18, MATRIX_B_18, MATRIX_C_18, MATRIX_D_18, MATRIX_E_18, MATRIX_F_18, MATRIX_G_18, MATRIX_H_18,
    INPUT_ROUTE_1, INPUT_ROUTE_2, INPUT_ROUTE_3, INPUT_ROUTE_4, INPUT_ROUTE_5, INPUT_ROUTE_6

};

struct MixSisCtrl
{

    static bool numidIsVolume(alsa_numid test);

    QSlider *vol_master[2];
    QCheckBox *vol_master_mute;
    QCheckBox *vol_master_link;
    QSlider *vol_out[6];
    QCheckBox *vol_out_mute[6];
    QCheckBox *vol_out_link[3];
    QComboBox *out_src[6];
    QComboBox *in_src[6];
    QRadioButton *in_imp[4];
    QRadioButton *in_pad[8];
    QComboBox *mtx_src[18];
    QSlider *mtx_vol[18][8];

    int save_to_dialog(QWidget *context);
    int load_from_dialog(QWidget *context);
    int load_from(QString &filename);
    int save_to(QString &filename);
    void set(int alsa_id, int value, int idx = 0);
};

#endif // MIXSISCTRL

